version: '3.1'

services:
    mysql:
        image: mysql:latest
        container_name: dev_db
        ports:
            - "3307:3306"
        env_file:
            - build/.env
    php:
        build: build/php-fpm
        ports:
            - '9002:9000'
        container_name: dev_app
        volumes:
            - ../:/var/www/html:consistent
            - ./logs/symfony:/var/www/html/var/logs:cached
        env_file:
            - build/.env
        links:
            - mysql
    nginx:
        build: build/nginx
        container_name: dev_web
        ports:
            - '8080:80'
        volumes:
            - ../:/var/www/html:consistent
            - ./logs/nginx/:/var/log/nginx:cached
        links:
            - php
